server {
    server_name ng_stack.test;
    listen 80;

    set $basedocroot  /var/www/html;
    set $docrootweb   /var/www/html/public;

    index index.php index.html;
    root /var/www/html/public;

    fastcgi_pass_header Authorization;

    location ^~ /var/ {
        deny all;
        return 403;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ ^/index\.php/(.*)$ {
        return 301 /$1;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        include fastcgi_params;
    }
}
